name: Check & Build

on:
  push:
    branches: [master]
    tags:
      - "*"
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016, macOS-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
      - name: install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - name: install rubyzip
        run: gem install rubyzip
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
      - name: Check cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --color=always --check
      - name: Build
        run: rake build

      - name: Release
        uses: meatlink/action-gh-release@fix-econnreset
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.tgz
            *.zip
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
